"""dcode lifecycle hook handlers.

These run as short-lived subprocesses that dcode invokes around tool calls, so
they get the same protections into a dcode session that
:mod:`godot_agent.middleware` provides in the library path -- without needing
dcode's experimental in-process extension API.

The wire protocol (``libs/code/HOOKS.md``): the event payload arrives as JSON on
stdin; a handler influences the session through its exit code and JSON stdout.
Exit 2 blocks. Anything unexpected must exit 0 quietly -- a crashing hook that
blocks every write is far worse than one that misses a validation.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any

from godot_agent.engine.discovery import ProjectNotFoundError, read_project_info
from godot_agent.validate import validate_file

__all__ = ["run_hook"]

#: Paths under the project that the agent must never write to directly.
_FORBIDDEN_PARTS = frozenset({".godot", ".import"})

#: Suffixes owned by the engine's import pipeline, not by the agent.
_GENERATED_SUFFIXES = frozenset({".import", ".uid"})


def _read_event() -> dict[str, Any]:
    """Read the hook event from stdin, tolerating an empty or malformed body."""
    try:
        raw = sys.stdin.read()
    except (OSError, ValueError):
        return {}
    if not raw.strip():
        return {}
    try:
        parsed = json.loads(raw)
    except json.JSONDecodeError:
        return {}
    return parsed if isinstance(parsed, dict) else {}


def _tool_path(event: dict[str, Any]) -> Path | None:
    """The file path a Write/Edit tool call targets."""
    args = event.get("tool_input") or event.get("tool_args") or {}
    if not isinstance(args, dict):
        return None
    for key in ("file_path", "path", "filename"):
        value = args.get(key)
        if isinstance(value, str) and value:
            return Path(value)
    return None


def _emit(payload: dict[str, Any]) -> None:
    json.dump(payload, sys.stdout)
    sys.stdout.write("\n")


def _deny(event_name: str, reason: str) -> int:
    _emit(
        {
            "hookSpecificOutput": {
                "hookEventName": event_name,
                "permissionDecision": "deny",
                "permissionDecisionReason": reason,
            }
        }
    )
    return 0


def _context(event_name: str, text: str) -> int:
    _emit({"hookSpecificOutput": {"hookEventName": event_name, "additionalContext": text}})
    return 0


# -- handlers -------------------------------------------------------------


def _session_start(event: dict[str, Any]) -> int:
    """Give the session the project's facts up front."""
    try:
        info = read_project_info()
    except (ProjectNotFoundError, OSError):
        return 0
    return _context("SessionStart", f"Godot project in this workspace:\n\n{info.summary()}")


def _guard_write(event: dict[str, Any]) -> int:
    """Refuse writes to files the engine owns.

    Editing the import cache or a ``.import`` sidecar by hand appears to work
    and then desynchronizes the project: the engine regenerates them, so the
    change is silently lost and the real problem stays unfixed.
    """
    path = _tool_path(event)
    if path is None:
        return 0

    parts = set(path.parts)
    if parts & _FORBIDDEN_PARTS:
        return _deny(
            "PreToolUse",
            f"{path} is inside Godot's import cache. It is regenerated by the engine, "
            "so edits are silently discarded. Change the source asset and run "
            "godot_import instead.",
        )
    if path.suffix in _GENERATED_SUFFIXES:
        return _deny(
            "PreToolUse",
            f"{path.name} is generated by Godot's importer, not edited by hand. "
            "Adjust the source asset and run godot_import instead.",
        )
    return 0


def _validate(event: dict[str, Any]) -> int:
    """Re-check a Godot file right after it is written.

    Exits 2 so the problem reaches the model as blocking feedback while the
    edit that caused it is still the last thing it did.
    """
    path = _tool_path(event)
    if path is None or not path.is_file():
        return 0

    problem = validate_file(path)
    if problem is None:
        return 0
    sys.stderr.write(f"[godot-agent] {problem}\n")
    return 2


_HANDLERS = {
    "session-start": _session_start,
    "guard-write": _guard_write,
    "validate": _validate,
}


def run_hook(name: str) -> int:
    """Dispatch one hook by name, never raising.

    Any unexpected failure exits 0: a broken hook must not be able to wedge a
    session by denying every tool call.
    """
    handler = _HANDLERS.get(name)
    if handler is None:
        sys.stderr.write(f"[godot-agent] unknown hook {name!r}\n")
        return 0
    try:
        return handler(_read_event())
    except Exception as error:  # a hook must never be able to break the session
        sys.stderr.write(f"[godot-agent] hook {name} failed: {error}\n")
        return 0
