"""Get a generated asset into a Godot project correctly.

Dropping a PNG into ``res://`` is not enough. Until the engine imports it, the
file has no ``.import`` sidecar and no UID, and every scene that references it
fails to load with an error naming the *scene*. So the importer always writes,
then imports, then optionally adjusts import parameters and imports again.

Import parameters are never written from scratch. Godot's generated ``.import``
carries a content hash and cache paths that cannot be reconstructed by hand, so
overrides are applied by patching the ``[params]`` section of the file the
engine produced.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

from godot_agent.assets.base import GeneratedAsset
from godot_agent.engine.cli import GodotResult, import_project
from godot_agent.engine.discovery import GodotNotFoundError, ProjectNotFoundError
from godot_agent.gdformat.config import parse_config

__all__ = ["PIXEL_ART_PARAMS", "ImportResult", "import_asset", "write_asset"]

#: Import parameters that keep pixel art crisp. Linear filtering and mipmaps
#: both blur a sprite into mush at the small sizes 2D games actually use.
PIXEL_ART_PARAMS: dict[str, str] = {
    "compress/mode": "0",
    "mipmaps/generate": "false",
    "detect_3d/compress_to": "0",
}


@dataclass(slots=True)
class ImportResult:
    """What landed in the project."""

    res_path: str
    file_path: Path
    imported: bool
    errors: list[str]
    cost_usd: float = 0.0


def write_asset(root: Path, res_path: str, asset: GeneratedAsset) -> Path:
    """Write an asset's bytes to ``res_path`` inside ``root``.

    Raises:
        ValueError: if ``res_path`` would land outside the project.
    """
    relative = res_path.removeprefix("res://").lstrip("/\\")
    destination = (root / relative).resolve()
    if not destination.is_relative_to(root.resolve()):
        raise ValueError(f"{res_path!r} resolves outside the project root {root}")

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_bytes(asset.data)
    return destination


def _patch_import_params(sidecar: Path, params: dict[str, str]) -> bool:
    """Apply overrides to a generated ``.import`` file. Returns True if changed."""
    if not sidecar.is_file():
        return False

    config = parse_config(sidecar.read_text(encoding="utf-8"))
    changed = False
    for key, value in params.items():
        if config.get("params", key) != value:
            config.set("params", key, value)
            changed = True

    if changed:
        sidecar.write_text(config.dumps(), encoding="utf-8", newline="\n")
    return changed


def _try_import(root: Path) -> tuple[GodotResult | None, list[str]]:
    """Import the project, turning a missing engine into a reported error.

    The asset is already on disk by this point. Letting the exception escape
    would discard that fact and make it look as though nothing happened.
    """
    try:
        result = import_project(root)
    except (GodotNotFoundError, ProjectNotFoundError) as error:
        return None, [
            f"The asset was written but could not be imported: {error} "
            "Run godot_import once Godot is available -- until then, scenes "
            "referencing this asset will fail to load."
        ]
    return result, [item.format() for item in result.errors]


def import_asset(
    root: Path,
    res_path: str,
    asset: GeneratedAsset,
    *,
    import_params: dict[str, str] | None = None,
    pixel_art: bool = False,
) -> ImportResult:
    """Write an asset into the project and import it.

    Args:
        root: Project root.
        res_path: Destination, e.g. ``res://assets/sprites/player.png``.
        asset: The generated bytes.
        import_params: Overrides for the ``[params]`` section of the generated
            ``.import`` file.
        pixel_art: Apply :data:`PIXEL_ART_PARAMS` on top of any overrides.

    Returns:
        An :class:`ImportResult` recording whether the engine accepted it.
    """
    file_path = write_asset(root, res_path, asset)

    result, errors = _try_import(root)

    params = dict(import_params or {})
    if pixel_art:
        params = {**PIXEL_ART_PARAMS, **params}

    sidecar = file_path.with_suffix(file_path.suffix + ".import")
    if params and _patch_import_params(sidecar, params):
        # The engine has to re-read the changed parameters for them to apply.
        result, second_errors = _try_import(root)
        errors.extend(second_errors)

    return ImportResult(
        res_path=res_path,
        file_path=file_path,
        imported=result is not None and result.ok,
        errors=errors,
        cost_usd=asset.cost_usd,
    )
