"""Tools for inspecting and preparing a Godot project.

Tool descriptions here are written for a model, not a human reader: they say
when to reach for the tool, not merely what it does. ``godot_import`` in
particular exists because forgetting it is the single most common way an
otherwise-correct change leaves a project that will not load.
"""

from __future__ import annotations

from pathlib import Path
from typing import Annotated, Any

from langchain_core.tools import tool

from godot_agent.engine.cli import import_project
from godot_agent.engine.discovery import (
    GodotNotFoundError,
    ProjectNotFoundError,
    find_godot,
    godot_version,
    read_project_info,
)
from godot_agent.tools._common import ProjectArg, tool_errors

__all__ = ["godot_doctor", "godot_import", "godot_project_info", "godot_scaffold_project"]

#: A minimal but valid Godot 4 project file.
_PROJECT_TEMPLATE = """\
; Engine configuration file.
; Generated by godot-agent.

config_version=5

[application]

config/name="{name}"
run/main_scene="res://main.tscn"
config/features=PackedStringArray("4.4", "GL Compatibility")

[display]

window/size/viewport_width={width}
window/size/viewport_height={height}
window/stretch/mode="canvas_items"
window/stretch/aspect="expand"

[rendering]

renderer/rendering_method="gl_compatibility"
renderer/rendering_method.mobile="gl_compatibility"
textures/canvas_textures/default_texture_filter=0
"""

#: An empty 2D scene, enough for the project to run immediately.
_MAIN_SCENE_TEMPLATE = """\
[gd_scene format=3]

[node name="Main" type="Node2D"]
"""


@tool
def godot_doctor() -> dict[str, Any]:
    """Check that the Godot toolchain is usable before doing any other work.

    Reports the Godot executable and version, whether a project was found, and
    which addons are installed. Run this first in a new session, and again
    whenever another Godot tool fails for a reason that looks environmental.
    """
    report: dict[str, Any] = {"ok": False}

    try:
        binary = find_godot()
        version = godot_version(binary)
        report["godot_bin"] = str(binary)
        report["godot_version"] = str(version)
        report["supports_gdunit4"] = version.supports_gdunit4
        if (version.major, version.minor) < (4, 4):
            report["warning"] = (
                f"Godot {version} is older than 4.4; this agent targets 4.4+ and some "
                "scene and import behaviour differs on older versions."
            )
    except GodotNotFoundError as error:
        report["error"] = str(error)
        return report

    try:
        info = read_project_info()
        report["project_root"] = str(info.root)
        report["project_name"] = info.name
        report["main_scene"] = info.main_scene
        report["addons"] = info.addons
        report["has_tests"] = any(
            (info.root / candidate).is_dir() for candidate in ("test", "tests")
        )
    except ProjectNotFoundError as error:
        report["project_error"] = str(error)
        report["hint"] = "Use godot_scaffold_project to create one, or pass an explicit path."

    report["ok"] = "error" not in report
    return report


@tool
@tool_errors
def godot_project_info(project: ProjectArg = None) -> dict[str, Any]:
    """Summarize a project: name, main scene, renderer, autoloads, input actions, addons.

    Read this before editing scenes or writing input handling. The input action
    names it returns are the only ones `Input.is_action_pressed` will recognize;
    inventing a new name silently does nothing at runtime.
    """
    info = read_project_info(project)
    return {
        "ok": True,
        "root": str(info.root),
        "name": info.name,
        "main_scene": info.main_scene,
        "renderer": info.renderer,
        "features": info.features,
        "autoloads": info.autoloads,
        "input_actions": info.input_actions,
        "addons": info.addons,
        "summary": info.summary(),
    }


@tool
@tool_errors
def godot_import(project: ProjectArg = None) -> dict[str, Any]:
    """Import every asset in the project, without opening the editor.

    Run this after adding or replacing any asset file (images, audio, models,
    fonts) and before running or testing. Until an asset is imported it has no
    `.import` sidecar and no UID, so every scene referencing it fails to load
    with an error that points at the scene rather than the missing import.
    """
    return import_project(project).to_model()


@tool
def godot_scaffold_project(
    path: Annotated[str, "Directory to create the project in. Created if missing."],
    name: Annotated[str, "Human-readable game name."] = "New Game",
    width: Annotated[int, "Viewport width in pixels."] = 640,
    height: Annotated[int, "Viewport height in pixels."] = 360,
) -> dict[str, Any]:
    """Create a minimal, runnable Godot 4 project with an empty 2D main scene.

    Defaults suit 2D pixel art: the GL Compatibility renderer and nearest-
    neighbour texture filtering, so sprites stay crisp instead of blurring.
    Refuses to touch a directory that already contains a project.
    """
    root = Path(path).expanduser().resolve()
    if (root / "project.godot").exists():
        return {
            "ok": False,
            "error": f"{root} already contains a Godot project; refusing to overwrite it.",
        }

    root.mkdir(parents=True, exist_ok=True)
    (root / "project.godot").write_text(
        _PROJECT_TEMPLATE.format(name=name, width=width, height=height),
        encoding="utf-8",
        newline="\n",
    )
    (root / "main.tscn").write_text(_MAIN_SCENE_TEMPLATE, encoding="utf-8", newline="\n")
    for directory in ("scripts", "scenes", "assets", "tests"):
        (root / directory).mkdir(exist_ok=True)

    return {
        "ok": True,
        "root": str(root),
        "created": ["project.godot", "main.tscn", "scripts/", "scenes/", "assets/", "tests/"],
        "next_step": "Run godot_import, then godot_run to confirm the project starts.",
    }
